server:
  port: 80
cors:
  originPatterns: http://localhost:**
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 18000000
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2k22.bpk@gmail.com
    password: alsjvzchendmnrwl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hackaton?useTimezone=true&serverTimezone=UTC
    username: root
    password: 134679895623215487
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
springdoc:
  pathsToMatch: 
  - /auth/**
  - /api/**
  swagger-ui:
    use-root-path: true